In [20]:
import numpy as np

In [44]:
a = np.array([[1,1,1,1],[2,2,2,2]])
print(a)
b = np.array([[1,2,3,4],[1,1,1,1],[1,2,1,9]])
print(b)
dists = np.zeros((2, 3))
for i in range(2):
      dists[i] = np.sqrt(np.sum(np.square(a[i] - b), axis=1))

[[1 1 1 1]
 [2 2 2 2]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 1 9]]


In [43]:
a

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [42]:
a[:,np.newaxis]

array([[[1, 1, 1, 1]],

       [[2, 2, 2, 2]]])

In [41]:
a[:,np.newaxis]-b

array([[[ 0, -1, -2, -3],
        [ 0,  0,  0,  0],
        [ 0, -1,  0, -8]],

       [[ 1,  0, -1, -2],
        [ 1,  1,  1,  1],
        [ 1,  0,  1, -7]]])

In [39]:
np.sum(a[0] - b, axis=1)

array([-6,  0, -9])

In [33]:
dists

array([[ 3.74165739,  0.        ,  8.06225775],
       [ 2.44948974,  2.        ,  7.14142843]])

In [46]:
np.sqrt(np.sum(np.square(a[:,np.newaxis] - b), axis=2))

array([[ 3.74165739,  0.        ,  8.06225775],
       [ 2.44948974,  2.        ,  7.14142843]])

In [50]:
a_2 = np.square(a[:,np.newaxis])
a_2

array([[[1, 1, 1, 1]],

       [[4, 4, 4, 4]]])

In [52]:
b_2 = np.square(b)
b_2

array([[ 1,  4,  9, 16],
       [ 1,  1,  1,  1],
       [ 1,  4,  1, 81]])

In [53]:
aSumSquare = np.sum(np.square(a),axis=1);
bSumSquare = np.sum(np.square(b),axis=1);
mul = np.dot(a,b.T);
dists = np.sqrt(aSumSquare[:,np.newaxis]+bSumSquare-2*mul)

In [54]:
dists

array([[ 3.74165739,  0.        ,  8.06225775],
       [ 2.44948974,  2.        ,  7.14142843]])

In [75]:
a = np.random.random((3, 4, 2))

In [76]:
a

array([[[ 0.13400624,  0.20676613],
        [ 0.02998039,  0.16872482],
        [ 0.05437827,  0.70727172],
        [ 0.23844832,  0.9963003 ]],

       [[ 0.81442465,  0.95770799],
        [ 0.94712798,  0.95237076],
        [ 0.57829651,  0.3425637 ],
        [ 0.82092028,  0.33676638]],

       [[ 0.08157554,  0.40861622],
        [ 0.44795942,  0.90283531],
        [ 0.30393712,  0.32319126],
        [ 0.70431881,  0.83840788]]])

In [81]:
np.vstack((a[0,:,:], a[2,:,:]))

array([[ 0.13400624,  0.20676613],
       [ 0.02998039,  0.16872482],
       [ 0.05437827,  0.70727172],
       [ 0.23844832,  0.9963003 ],
       [ 0.08157554,  0.40861622],
       [ 0.44795942,  0.90283531],
       [ 0.30393712,  0.32319126],
       [ 0.70431881,  0.83840788]])